# Generated by Django 2.2.2 on 2019-07-08 19:32

import colorfield.fields
from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('icon', faicon.fields.FAIconField(max_length=50)),
                ('bg_color', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
            ],
        ),
    ]
