# Generated by Django 2.2.2 on 2019-07-09 07:43

import colorfield.fields
from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('first_sm_url', models.CharField(max_length=255)),
                ('first_sm_icon', faicon.fields.FAIconField(max_length=50)),
                ('second_sm_url', models.CharField(max_length=255)),
                ('second_sm_icon', faicon.fields.FAIconField(max_length=50)),
                ('third_sm_url', models.CharField(max_length=255)),
                ('third_sm_icon', faicon.fields.FAIconField(max_length=50)),
                ('logo', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
