# Generated by Django 2.2.2 on 2019-07-09 08:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_year', models.IntegerField(default=2019, max_length=4)),
                ('copyright_for', models.CharField(default='akramakh', max_length=100)),
                ('site_name', models.CharField(default='Portfolio', max_length=100)),
                ('bg_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
        ),
    ]
