# Generated by Django 2.2.2 on 2019-07-09 08:40

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('bg_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('icon', faicon.fields.FAIconField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='header',
            name='first_sm_icon',
        ),
        migrations.RemoveField(
            model_name='header',
            name='first_sm_url',
        ),
        migrations.RemoveField(
            model_name='header',
            name='second_sm_icon',
        ),
        migrations.RemoveField(
            model_name='header',
            name='second_sm_url',
        ),
        migrations.RemoveField(
            model_name='header',
            name='third_sm_icon',
        ),
        migrations.RemoveField(
            model_name='header',
            name='third_sm_url',
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_year',
            field=models.CharField(default='2019', max_length=4),
        ),
        migrations.AddField(
            model_name='header',
            name='first_sm_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_sm_account', to='main.SocialMedia'),
        ),
        migrations.AddField(
            model_name='header',
            name='second_sm_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_sm_account', to='main.SocialMedia'),
        ),
        migrations.AddField(
            model_name='header',
            name='third_sm_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_sm_account', to='main.SocialMedia'),
        ),
    ]
